package com.cyberguardian.quest

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// Data Models
data class Scenario(
    val id: Int,
    val topic: String,
    val question: String,
    val correctAction: String,
    val explanation: String
)

// Static Content - Generated by LLM
val scenarios = listOf(
    // Passwords (5 scenarios)
    Scenario(1, "Passwords", "Your best friend asks to borrow your tablet password to play a game. What should you do?", "Unsafe Action", "Never share your password, even with friends. Ask a parent to help set up a guest account instead."),
    Scenario(2, "Passwords", "You want to use 'password123' for your new game account. Is this a good idea?", "Unsafe Action", "Simple passwords are easy to guess. Use a mix of letters, numbers, and symbols to stay safe."),
    Scenario(3, "Passwords", "Mom says to write down your school login password in a secret notebook only you can access. Should you do it?", "Safe Action", "Writing passwords in a private, secure place that only you and your parents know about is okay."),
    Scenario(4, "Passwords", "A website asks you to create a password. You use your pet's name. Is this safe?", "Unsafe Action", "Pet names are easy for others to guess. Choose something more unique and harder to figure out."),
    Scenario(5, "Passwords", "You use a different password for each of your accounts. Is this a smart choice?", "Safe Action", "Using different passwords for each account keeps you extra safe if one gets discovered."),

    // Private Information (7 scenarios)
    Scenario(6, "Private Information", "Someone in an online game asks where you go to school. Should you tell them?", "Unsafe Action", "Never share your school name online. Strangers don't need to know where you are."),
    Scenario(7, "Private Information", "A fun quiz asks for your home address to send you a prize. Should you enter it?", "Unsafe Action", "Never give your address to websites or strangers. Ask a parent first if something seems important."),
    Scenario(8, "Private Information", "You're making an avatar and it asks for a username. You choose 'CoolGamer2024' instead of your real name. Good choice?", "Safe Action", "Using a fun username instead of your real name helps keep your identity private online."),
    Scenario(9, "Private Information", "A new online friend asks for your phone number to text you. Should you share it?", "Unsafe Action", "Keep your phone number private. Only share it with people you know in real life and with parent permission."),
    Scenario(10, "Private Information", "You're chatting in a game and someone asks your age. You say 'I'm a kid' instead of your exact age. Smart move?", "Safe Action", "Being vague about personal details like your exact age helps protect your privacy online."),
    Scenario(11, "Private Information", "A website wants to know your favorite color for your profile. Is it okay to answer?", "Safe Action", "Sharing general preferences like favorite colors is usually safe - it doesn't reveal who or where you are."),
    Scenario(12, "Private Information", "Someone asks for a photo of you for their 'friends gallery'. Should you send it?", "Unsafe Action", "Never send photos of yourself to people you don't know in real life. Always ask a parent first."),

    // Phishing/Stranger Danger (8 scenarios)
    Scenario(13, "Phishing", "You get a message saying 'Click here to get 1000 free coins!' Should you click it?", "Unsafe Action", "These messages are tricks to steal information. Never click suspicious links promising free stuff."),
    Scenario(14, "Phishing", "An email says your account will be deleted unless you click a link right now. What should you do?", "Unsafe Action", "Scary messages trying to rush you are usually scams. Tell a parent before clicking anything."),
    Scenario(15, "Phishing", "A stranger online offers to give you rare game items if you log in to their website. Should you?", "Unsafe Action", "This is a trap to steal your login. Never enter your password on sites strangers send you."),
    Scenario(16, "Phishing", "You get a message from someone you don't know. You ignore it and tell your parents. Good choice?", "Safe Action", "Ignoring messages from strangers and telling a trusted adult is exactly the right thing to do."),
    Scenario(17, "Phishing", "A pop-up says your device has a virus and to call a number immediately. Should you call?", "Unsafe Action", "These are fake warnings to scare you. Close the pop-up and tell an adult - don't call the number."),
    Scenario(18, "Phishing", "Someone you just met online wants to video chat with you. You say no and log off. Smart move?", "Safe Action", "Never video chat with online strangers. You made the safe choice by saying no and leaving."),
    Scenario(19, "Phishing", "A message claims to be from your favorite game, but the spelling looks weird. You delete it. Good thinking?", "Safe Action", "Real companies use correct spelling. Suspicious messages should be deleted and reported to an adult."),
    Scenario(20, "Phishing", "An ad promises a free phone if you enter your parent's credit card. Should you do it?", "Unsafe Action", "Never enter payment information, especially your parents'. These are scams to steal money.")
)

// Game States
enum class GameState {
    WELCOME, PLAYING, RESULTS
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            CyberGuardianQuestTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    CyberGuardianQuestApp()
                }
            }
        }
    }
}

@Composable
fun CyberGuardianQuestTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = lightColorScheme(
            primary = Color(0xFF6200EE),
            secondary = Color(0xFF03DAC6),
            background = Color(0xFFF5F5F5)
        ),
        content = content
    )
}

@Composable
fun CyberGuardianQuestApp() {
    var gameState by remember { mutableStateOf(GameState.WELCOME) }
    var currentQuestionIndex by remember { mutableStateOf(0) }
    var score by remember { mutableStateOf(0) }
    var showFeedback by remember { mutableStateOf(false) }
    var isCorrect by remember { mutableStateOf(false) }
    var selectedAction by remember { mutableStateOf("") }

    when (gameState) {
        GameState.WELCOME -> WelcomeScreen(
            onStartGame = {
                gameState = GameState.PLAYING
                currentQuestionIndex = 0
                score = 0
                showFeedback = false
            }
        )
        GameState.PLAYING -> GameScreen(
            scenario = scenarios[currentQuestionIndex],
            currentQuestion = currentQuestionIndex + 1,
            totalQuestions = scenarios.size,
            score = score,
            showFeedback = showFeedback,
            isCorrect = isCorrect,
            selectedAction = selectedAction,
            onAnswerSelected = { action ->
                selectedAction = action
                isCorrect = action == scenarios[currentQuestionIndex].correctAction
                if (isCorrect) score++
                showFeedback = true
            },
            onNextQuestion = {
                showFeedback = false
                if (currentQuestionIndex < scenarios.size - 1) {
                    currentQuestionIndex++
                } else {
                    gameState = GameState.RESULTS
                }
            }
        )
        GameState.RESULTS -> ResultsScreen(
            score = score,
            totalQuestions = scenarios.size,
            onPlayAgain = {
                gameState = GameState.WELCOME
            }
        )
    }
}

@Composable
fun WelcomeScreen(onStartGame: () -> Unit) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(
                        Color(0xFF667EEA),
                        Color(0xFF764BA2)
                    )
                )
            )
            .padding(24.dp),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            // Robot Mascot
            Text(
                text = "🤖",
                fontSize = 120.sp,
                modifier = Modifier.padding(bottom = 24.dp)
            )

            // Title
            Text(
                text = "Cyber Guardian Quest",
                fontSize = 36.sp,
                fontWeight = FontWeight.Bold,
                color = Color.White,
                textAlign = TextAlign.Center,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            // Subtitle
            Text(
                text = "Learn to stay safe online!",
                fontSize = 18.sp,
                color = Color.White.copy(alpha = 0.9f),
                textAlign = TextAlign.Center,
                modifier = Modifier.padding(bottom = 48.dp)
            )

            // Start Button
            Button(
                onClick = onStartGame,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(60.dp),
                colors = ButtonDefaults.buttonColors(
                    containerColor = Color(0xFF4CAF50)
                ),
                shape = RoundedCornerShape(30.dp)
            ) {
                Text(
                    text = "🚀 Start Mission",
                    fontSize = 20.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}

@Composable
fun GameScreen(
    scenario: Scenario,
    currentQuestion: Int,
    totalQuestions: Int,
    score: Int,
    showFeedback: Boolean,
    isCorrect: Boolean,
    selectedAction: String,
    onAnswerSelected: (String) -> Unit,
    onNextQuestion: () -> Unit
) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFF5F5F5))
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp)
        ) {
            // Progress Header
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 16.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                elevation = CardDefaults.cardElevation(4.dp)
            ) {
                Column(
                    modifier = Modifier.padding(16.dp)
                ) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Text(
                            text = "Question $currentQuestion/$totalQuestions",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color(0xFF667EEA)
                        )
                        Text(
                            text = "Score: $score",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color(0xFF4CAF50)
                        )
                    }

                    Spacer(modifier = Modifier.height(8.dp))

                    LinearProgressIndicator(
                        progress = currentQuestion.toFloat() / totalQuestions,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(8.dp),
                        color = Color(0xFF667EEA),
                        trackColor = Color(0xFFE0E0E0)
                    )
                }
            }

            // Topic Badge
            Surface(
                modifier = Modifier.padding(bottom = 16.dp),
                color = when (scenario.topic) {
                    "Passwords" -> Color(0xFFFF9800)
                    "Private Information" -> Color(0xFF2196F3)
                    else -> Color(0xFFE91E63)
                },
                shape = RoundedCornerShape(20.dp)
            ) {
                Text(
                    text = "📚 ${scenario.topic}",
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
                    color = Color.White,
                    fontWeight = FontWeight.Bold
                )
            }

            // Scenario Card
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                elevation = CardDefaults.cardElevation(8.dp)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(24.dp)
                        .verticalScroll(rememberScrollState()),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {
                    // Scenario Icon
                    Text(
                        text = when (scenario.topic) {
                            "Passwords" -> "🔐"
                            "Private Information" -> "🛡️"
                            else -> "⚠️"
                        },
                        fontSize = 64.sp,
                        modifier = Modifier.padding(bottom = 24.dp)
                    )

                    // Question
                    Text(
                        text = scenario.question,
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Medium,
                        textAlign = TextAlign.Center,
                        color = Color(0xFF333333),
                        lineHeight = 28.sp
                    )

                    Spacer(modifier = Modifier.height(32.dp))

                    if (!showFeedback) {
                        // Action Buttons
                        Button(
                            onClick = { onAnswerSelected("Safe Action") },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(60.dp),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = Color(0xFF4CAF50)
                            ),
                            shape = RoundedCornerShape(16.dp)
                        ) {
                            Text(
                                text = "✅ Safe Action",
                                fontSize = 18.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }

                        Spacer(modifier = Modifier.height(16.dp))

                        Button(
                            onClick = { onAnswerSelected("Unsafe Action") },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(60.dp),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = Color(0xFFF44336)
                            ),
                            shape = RoundedCornerShape(16.dp)
                        ) {
                            Text(
                                text = "❌ Unsafe Action",
                                fontSize = 18.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    } else {
                        // Feedback Card
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(
                                containerColor = if (isCorrect)
                                    Color(0xFFE8F5E9)
                                else
                                    Color(0xFFFFEBEE)
                            ),
                            shape = RoundedCornerShape(16.dp)
                        ) {
                            Column(
                                modifier = Modifier.padding(20.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                Text(
                                    text = if (isCorrect) "🎉 Correct!" else "💭 Not Quite!",
                                    fontSize = 24.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = if (isCorrect)
                                        Color(0xFF4CAF50)
                                    else
                                        Color(0xFFF44336),
                                    modifier = Modifier.padding(bottom = 12.dp)
                                )

                                Text(
                                    text = scenario.explanation,
                                    fontSize = 16.sp,
                                    textAlign = TextAlign.Center,
                                    color = Color(0xFF333333),
                                    lineHeight = 22.sp
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(24.dp))

                        Button(
                            onClick = onNextQuestion,
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(56.dp),
                            colors = ButtonDefaults.buttonColors(
                                containerColor = Color(0xFF667EEA)
                            ),
                            shape = RoundedCornerShape(16.dp)
                        ) {
                            Text(
                                text = if (currentQuestion < totalQuestions)
                                    "Next Question →"
                                else
                                    "See Results →",
                                fontSize = 18.sp,
                                fontWeight = FontWeight.Bold
                            )
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun ResultsScreen(
    score: Int,
    totalQuestions: Int,
    onPlayAgain: () -> Unit
) {
    val percentage = (score.toFloat() / totalQuestions * 100).toInt()

    val (message, emoji, color) = when {
        percentage >= 90 -> Triple(
            "Outstanding! You're a true Cyber Guardian! You know how to stay safe online.",
            "🏆",
            Color(0xFFFFD700)
        )
        percentage >= 75 -> Triple(
            "Excellent work, future analyst! You've got strong online safety skills.",
            "⭐",
            Color(0xFF4CAF50)
        )
        percentage >= 60 -> Triple(
            "Good job! You're learning fast. Keep practicing to become a cyber expert!",
            "👍",
            Color(0xFF2196F3)
        )
        else -> Triple(
            "Nice try! Every guardian starts somewhere. Play again to improve your skills!",
            "💪",
            Color(0xFFFF9800)
        )
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(
                        Color(0xFF667EEA),
                        Color(0xFF764BA2)
                    )
                )
            )
            .padding(24.dp),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            // Trophy/Badge
            Text(
                text = emoji,
                fontSize = 100.sp,
                modifier = Modifier.padding(bottom = 24.dp)
            )

            // Mission Complete
            Text(
                text = "Mission Complete!",
                fontSize = 32.sp,
                fontWeight = FontWeight.Bold,
                color = Color.White,
                textAlign = TextAlign.Center,
                modifier = Modifier.padding(bottom = 16.dp)
            )

            // Score Card
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 24.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White),
                elevation = CardDefaults.cardElevation(8.dp),
                shape = RoundedCornerShape(20.dp)
            ) {
                Column(
                    modifier = Modifier.padding(32.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Text(
                        text = "Your Score",
                        fontSize = 18.sp,
                        color = Color.Gray,
                        modifier = Modifier.padding(bottom = 8.dp)
                    )

                    Text(
                        text = "$score / $totalQuestions",
                        fontSize = 48.sp,
                        fontWeight = FontWeight.Bold,
                        color = color
                    )

                    Text(
                        text = "$percentage% Correct",
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Medium,
                        color = Color.Gray,
                        modifier = Modifier.padding(top = 8.dp)
                    )
                }
            }

            // Personalized Message
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 32.dp),
                colors = CardDefaults.cardColors(
                    containerColor = Color.White.copy(alpha = 0.95f)
                ),
                shape = RoundedCornerShape(16.dp)
            ) {
                Text(
                    text = message,
                    fontSize = 16.sp,
                    textAlign = TextAlign.Center,
                    color = Color(0xFF333333),
                    lineHeight = 24.sp,
                    modifier = Modifier.padding(20.dp)
                )
            }

            // Play Again Button
            Button(
                onClick = onPlayAgain,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(60.dp),
                colors = ButtonDefaults.buttonColors(
                    containerColor = Color(0xFF4CAF50)
                ),
                shape = RoundedCornerShape(30.dp)
            ) {
                Text(
                    text = "🔄 Play Again",
                    fontSize = 20.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}
